### ISSUE TITLE
asdf-nodejs friendly nvmrc

### ISSUE THREAD

**Issue by olets** [hirusi/smix-eleventy-starter#24]
asdf-nodejs needs a full version specification, not just a major version. So for example

```shell
# .nvmc
lts/erbium
v12.x.y
```

I'd be happy to open a pull request for this change. If that sounds good to you, do you have a preferred version? Latest 12.x is 12.20.0

**Comment by hirusi** [comment]
I don't know how `asdf-nodejs` works but this is a fair request. Does it affect how `nvm` would work?

Out of curiosity, how does it keep up with minor or patch version releases short of editing the `.nvmrc`?

**Comment by olets** [comment]
> Would this affect how nvm works?

I believe no. nvm seems to only look at the first option — it doesn't cascade. For example, the latest 12.x I have installed with nvm is 12.16.3, and I don't have lts/erbium installed with nvm. If I change the Smix nvmrc to

```shell
lts/erbium
v12.16.3
```

nvm insists on using lts/erbium:

```shell
% nvm use
Found 'snip/.nvmrc' with version <lts/erbium>
N/A: version "lts/erbium -> N/A" is not yet installed.

You need to run "nvm install lts/erbium" to install it before using it.
```

> how does the former keep up with minor or patch version releases short of editing the .nvmrc each time?

It doesn't. Which is a good point: my proposal might not be a good fit for this project if you're updating for each Erbium release. Looking at the package-lock I think you might be

**Comment by hirusi** [comment]
I'm not necessarily updating for each minor/patch release. Since it's semver, I'd like for folks who `npm install`, whenever they clone it, to get those fixes from the recent releases since it doesn't (shouldn't) cause breaking changes.

Since this does not interrupt my workflow with nvm, I'm happy to have it in if you wish to open a PR. Probably worth putting a note in the README.
